- name: "compute/instance/delete: ensure state of instance"
  gce:
    service_account_email: "{{ gce.client_email }}"
    credentials_file: "{{ gce.credentials_file }}"
    project_id: "{{ gce.project_id }}"
    zone: "{{ gce.zone }}"
    name: "{{ gce_compute_instance_entry.name }}"
    state: "{{ gce_compute_instance_state }}"
  register: r_gce_compute_instance
  loop: "{{ gce.compute.instances }}"
  loop_control:
    loop_var: gce_compute_instance_entry

- debug:
    var: r_gce_compute_instance
    verbosity: 2
