- name: "network/firewall/delete: ensure state of firewall rules"
  gce_net:
    service_account_email: "{{ gce.client_email }}"
    credentials_file: "{{ gce.credentials_file }}"
    project_id: "{{ gce.project_id }}"
    name: "{{ gce.network.firewall.name }}"
    fwrule: "{{ gce_network_firewall_entry.name }}"
    state: "{{ gce_network_firewall_entry.state | default(gce_network_firewall_states[gce_action]) }}"
  register: r_gce_network_firewall
  loop: "{{ gce.network.firewall.rules | default([]) }}"
  loop_control:
    loop_var: gce_network_firewall_entry

- debug:
    var: r_gce_network_firewall
    verbosity: 2
