compute:
  instance:
    name: darkbulb
    image: "nested-centos-7"

    network:
      subnets: "{{ network.subnets }}"

    security:
      policies: "{{ network.security.policies }}"

    hardware:
      #type: "n1-standard-16"
      type: "n1-standard-1"
      disks: "{{ storage.target.volumes }}"
      interfaces: "{{ network.veth.ports }}"
    tags:
      - darkbulb
