---
- name: "delete"
  block:
    - include_vars: vars/sanity.yml
    - include_vars: vars/compute.yml
    - include_vars: vars/storage.yml
    - include_vars: vars/network.yml
    - include_vars: vars/inventory.yml
    - include_vars: vars/assert.yml
    - include_vars: vars/rescue.yml
    - include_vars: vars/run.yml

    - include_tasks: sanity.yml
    - include_tasks: compute.yml
    - include_tasks: storage.yml
    - include_tasks: network.yml
    - include_tasks: inventory.yml
    - include_tasks: assert.yml

  rescue:
    - include_tasks: rescue.yml
  when: "'delete' is in gce_action"
