---
## GCE Global
gce_region: europe-west1
gce_zone: europe-west1-d
gce_credentials_file: ''
gce_project_id: ''
gce_client_email: ''
gce_network: {}
gce_compute: {}
gce_storage: {}
gce_action: create
