- name: "kubeshift: Load variables"
  include_vars:
    file: "kubeshift.yml"

- name: "kubeshift: Ensure state of git repositories"
  git:
    repo: "{{ kubeshift_git_entry.value.src }}"
    version: "{{ kubeshift_git_entry.value.version }}"
    clone: "{{ kubeshift_git_entry.value.clone }}"
    dest: "{{ kubeshift_git_entry.value.dest }}"
    force: "{{ kubeshift_git_entry.value.force }}"
  with_dict: "{{ kubeshift_git_dict | default({}) }}"
  loop_control:
    loop_var: kubeshift_git_entry
  tags:
    - install
